version: '3.8'
services:
  proxy:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./n.conf:/etc/nginx/conf.d/default.conf
      - ./wp-data:/var/www/html
    links:
      - wordpress
    restart: always
  wordpress:
    image: wordpress:php8.1-apache
    ports:
      - '8080:80'
    volumes:
      - ./wp-data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${MYSQLdbname}
      - WORDPRESS_DB_PASSWORD=${MYSQLpassword}
      - WORDPRESS_DB_USER=${MYSQLuser}
      - WORDPRESS_DB_HOST=database-1.cvukcq8h6dzb.us-east-1.rds.amazonaws.com

    restart: always
